version: '3'
services:
  database:
    image: mysql
    container_name: "flexisource"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flexisource
      MYSQL_USER: admin
      MYSQL_PASSWORD: Abc123
      MYSQL_ROOT_PASSWORD: Abc123
    restart: on-failure
    volumes:
      - persistent:/var/lib/mysql
    networks:
      default:
        aliases:
        - flexisource
volumes:
  persistent: