version: '4'
services:
  database:
    image: mysql
    container_name: "flexisource"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Abc1234
    restart: on-failure
    volumes:
      - persistent:/var/lib/mysql
    networks:
      default:
        aliases:
        - flexisource
volumes:
  persistent: